// <auto-generated />
using System;
using Core.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230216160724_AddTablesGenresAuthorsBooksGenresInBooks")]
    partial class AddTablesGenresAuthorsBooksGenresInBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Persistence.Entities.Authors", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("AuthorFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            AuthorFirstName = "J.K",
                            AuthorLastName = "Rowling"
                        },
                        new
                        {
                            AuthorId = 2,
                            AuthorFirstName = "J.R.R",
                            AuthorLastName = "Tolkien"
                        },
                        new
                        {
                            AuthorId = 3,
                            AuthorFirstName = "Jane",
                            AuthorLastName = "Austen"
                        },
                        new
                        {
                            AuthorId = 4,
                            AuthorFirstName = "John",
                            AuthorLastName = "Green"
                        },
                        new
                        {
                            AuthorId = 5,
                            AuthorFirstName = "Nicholas",
                            AuthorLastName = "Sparks"
                        },
                        new
                        {
                            AuthorId = 6,
                            AuthorFirstName = "Rainbow",
                            AuthorLastName = "Rowell"
                        },
                        new
                        {
                            AuthorId = 7,
                            AuthorFirstName = "Agatha",
                            AuthorLastName = "Christie"
                        },
                        new
                        {
                            AuthorId = 8,
                            AuthorFirstName = "Gillian",
                            AuthorLastName = "Flynn"
                        },
                        new
                        {
                            AuthorId = 9,
                            AuthorFirstName = "Dan",
                            AuthorLastName = "Brown"
                        },
                        new
                        {
                            AuthorId = 10,
                            AuthorFirstName = "Holly",
                            AuthorLastName = "Jackson"
                        },
                        new
                        {
                            AuthorId = 11,
                            AuthorFirstName = "Bill",
                            AuthorLastName = "Bryson"
                        },
                        new
                        {
                            AuthorId = 12,
                            AuthorFirstName = "Jon",
                            AuthorLastName = "Krakauer"
                        },
                        new
                        {
                            AuthorId = 13,
                            AuthorFirstName = "Stephen",
                            AuthorLastName = "King"
                        },
                        new
                        {
                            AuthorId = 14,
                            AuthorFirstName = "Shirly",
                            AuthorLastName = "Jackson"
                        },
                        new
                        {
                            AuthorId = 15,
                            AuthorFirstName = "Bram",
                            AuthorLastName = "Stoker"
                        },
                        new
                        {
                            AuthorId = 16,
                            AuthorFirstName = "Mathew",
                            AuthorLastName = "Walker"
                        },
                        new
                        {
                            AuthorId = 17,
                            AuthorFirstName = "Michael",
                            AuthorLastName = "Pollan"
                        },
                        new
                        {
                            AuthorId = 18,
                            AuthorFirstName = "Irma S.",
                            AuthorLastName = "Rombauer"
                        },
                        new
                        {
                            AuthorId = 19,
                            AuthorFirstName = "Julia",
                            AuthorLastName = "Child"
                        });
                });

            modelBuilder.Entity("Core.Persistence.Entities.Books", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublicationYear")
                        .HasColumnType("DATE");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            BookTitle = "Harry Potter and the Philosopher’s Stone (Harry Potter #1)",
                            PublicationYear = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Harry Potter thinks he is an ordinary boy - until he is rescued by an owl, taken to Hogwarts School of Witchcraft and Wizardry, learns to play Quidditch and does battle in a deadly duel. The Reason ... HARRY POTTER IS A WIZARD!"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 1,
                            BookTitle = "Harry Potter and the Chamber of Secrets (Harry Potter #2)",
                            PublicationYear = new DateTime(1998, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Ever since Harry Potter had come home for the summer, the Dursleys had been so mean and hideous that all Harry wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he’s packing his bags, Harry receives a warning from a strange impish creature who says that if Harry returns to Hogwarts, disaster will strike. And strike it does. For in Harry’s second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor and a spirit who haunts the girls’ bathroom. But then the real trouble begins – someone is turning Hogwarts students to stone. Could it be Draco Malfoy, a more poisonous rival than ever? Could it possibly be Hagrid, whose mysterious past is finally told? Or could it be the one everyone at Hogwarts most suspects… Harry Potter himself!"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 1,
                            BookTitle = "Harry Potter and the Prisoner of Azkaban (Harry Potter #3)",
                            PublicationYear = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Harry Potter, along with his best friends, Ron and Hermione, is about to start his third year at Hogwarts School of Witchcraft and Wizardry. Harry can't wait to get back to school after the summer holidays. (Who wouldn't if they lived with the horrible Dursleys?) But when Harry gets to Hogwarts, the atmosphere is tense. There's an escaped mass murderer on the loose, and the sinister prison guards of Azkaban have been called in to guard the school..."
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 1,
                            BookTitle = "Harry Potter and the Goblet of Fire (Harry Potter #4)",
                            PublicationYear = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "It is the summer holidays and soon Harry Potter will be starting his fourth year at Hogwarts School of Witchcraft and Wizardry. Harry is counting the days: there are new spells to be learnt, more Quidditch to be played, and Hogwarts castle to continue exploring. But Harry needs to be careful - there are unexpected dangers lurking..."
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 1,
                            BookTitle = "Harry Potter and the Order of the Phoenix (Harry Potter #5)",
                            PublicationYear = new DateTime(2003, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Harry Potter is about to start his fifth year at Hogwarts School of Witchcraft and Wizardry. Unlike most schoolboys, Harry never enjoys his summer holidays, but this summer is even worse than usual. The Dursleys, of course, are making his life a misery, but even his best friends, Ron and Hermione, seem to be neglecting him. Harry has had enough. He is beginning to think he must do something, anything, to change his situation, when the summer holidays come to an end in a very dramatic fashion. What Harry is about to discover in his new year at Hogwarts will turn his world upside down..."
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 1,
                            BookTitle = "Harry Potter and the Half-Blood Prince (Harry Potter #6)",
                            PublicationYear = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "It is the middle of the summer, but there is an unseasonal mist pressing against the windowpanes. Harry Potter is waiting nervously in his bedroom at the Dursleys' house in Privet Drive for a visit from Professor Dumbledore himself. One of the last times he saw the Headmaster was in a fierce one-to-one duel with Lord Voldemort, and Harry can't quite believe that Professor Dumbledore will actually appear at the Dursleys' of all places. Why is the Professor coming to visit him now? What is it that cannot wait until Harry returns to Hogwarts in a few weeks' time? Harry's sixth year at Hogwarts has already got off to an unusual start, as the worlds of Muggle and magic start to intertwine..."
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 1,
                            BookTitle = "Harry Potter and the Deathly Hallows (Harry Potter #7)",
                            PublicationYear = new DateTime(2007, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Harry has been burdened with a dark, dangerous and seemingly impossible task: that of locating and destroying Voldemort's remaining Horcruxes. Never has Harry felt so alone, or faced a future so full of shadows. But Harry must somehow find within himself the strength to complete the task he has been given. He must leave the warmth, safety and companionship of The Burrow and follow without fear or hesitation the inexorable path laid out for him... In this final, seventh installment of the Harry Potter series, J.K. Rowling unveils in spectacular fashion the answers to the many questions that have been so eagerly awaited."
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 1,
                            BookTitle = "Harry Potter and the Cursed Child: Parts One and Two (Harry Potter #8)",
                            PublicationYear = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "The eighth story, nineteen years later... It was always difficult being Harry Potter, and it isn't much easier now that he is an overworked employee of the Ministry of Magic, a husband, and a father of three school-age children. While Harry grapples with a past that refuses to stay where it belongs, his youngest son, Albus, must struggle with the weight of a family legacy he never wanted. As past and present fuse ominously, both father and son learn the uncomfortable truth: sometimes, darkness comes from unexpected places. Based on an original new story by J.K. Rowling, Jack Thorne, and John Tiffany, a new play by Jack Thorne, \"Harry Potter and the Cursed Child\" is the complete and official playscript of the original, award-winning West End production. This updated edition includes the final dialogue and stage directions, a conversation piece between director John Tiffany and playwright Jack Thorne, the Potter family tree, and a timeline of events in the wizarding world leading up to \"Harry Potter and the Cursed Child.\""
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 2,
                            BookTitle = "The Hobbit (The Lord of the Rings #0)",
                            PublicationYear = new DateTime(1937, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "n a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort.\r\nWritten for J.R.R. Tolkien’s own children, The Hobbit met with instant critical acclaim when it was first published in 1937. Now recognized as a timeless classic, this introduction to the hobbit Bilbo Baggins, the wizard Gandalf, Gollum, and the spectacular world of Middle-earth recounts of the adventures of a reluctant hero, a powerful and dangerous ring, and the cruel dragon Smaug the Magnificent. The text in this 372-page paperback edition is based on that first published in Great Britain by Collins Modern Classics (1998), and includes a note on the text by Douglas A. Anderson (2001)."
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 2,
                            BookTitle = "The Fellowship of the Ring (The Lord of the Rings #1)",
                            PublicationYear = new DateTime(1954, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them. In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose."
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 2,
                            BookTitle = "The Two Towers (The Lord of the Rings #2)",
                            PublicationYear = new DateTime(1954, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Begin your journey into Middle-earth. The inspiration for the upcoming original series on Prime Video, The Lord of the Rings: The Rings of Power. The Two Towers is the second part of J.R.R. Tolkien’s epic adventure The Lord of the Rings. One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them. Frodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in a battle in the Mines of Moria. And Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape, the rest of the company was attacked by Orcs. Now they continue the journey alone down the great River Anduin—alone, that is, save for the mysterious creeping figure that follows wherever they go."
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 2,
                            BookTitle = "The Return of the King (The Lord of the Rings #3)",
                            PublicationYear = new DateTime(1955, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Begin your journey into Middle-earth. The inspiration for the upcoming original series on Prime Video, The Lord of the Rings: The Rings of Power. The Return of the King is the third part of J.R.R. Tolkien’s epic adventure The Lord of the Rings. One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them. The Dark Lord has risen, and as he unleashes hordes of Orcs to conquer all Middle-earth, Frodo and Sam struggle deep into his realm in Mordor. To defeat Sauron, the One Ring must be destroyed in the fires of Mount Doom. But the way is impossibly hard, and Frodo is weakening. The Ring corrupts all who bear it and Frodo’s time is running out. Will Sam and Frodo succeed, or will the Dark Lord rule Middle-earth once more?"
                        },
                        new
                        {
                            BookId = 13,
                            AuthorId = 3,
                            BookTitle = "Pride and Prejudice",
                            PublicationYear = new DateTime(1813, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work \"her own darling child\" and its vivacious heroine, Elizabeth Bennet, \"as delightful a creature as ever appeared in print.\" The romantic clash between the opinionated Elizabeth and her proud beau, Mr. Darcy, is a splendid performance of civilized sparring. And Jane Austen's radiant wit sparkles as her characters dance a delicate quadrille of flirtation and intrigue, making this book the most superb comedy of manners of Regency England."
                        },
                        new
                        {
                            BookId = 14,
                            AuthorId = 4,
                            BookTitle = "The Fault in Our Stars",
                            PublicationYear = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a gorgeous plot twist named Augustus Waters suddenly appears at Cancer Kid Support Group, Hazel's story is about to be completely rewritten. Insightful, bold, irreverent, and raw, The Fault in Our Stars is award-winning author John Green's most ambitious and heartbreaking work yet, brilliantly exploring the funny, thrilling, and tragic business of being alive and in love."
                        },
                        new
                        {
                            BookId = 15,
                            AuthorId = 4,
                            BookTitle = "Looking for Alaska",
                            PublicationYear = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Before. Miles “Pudge” Halter is done with his safe life at home. His whole life has been one big non-event, and his obsession with famous last words has only made him crave “the Great Perhaps” even more (Francois Rabelais, poet). He heads off to the sometimes crazy and anything-but-boring world of Culver Creek Boarding School, and his life becomes the opposite of safe. Because down the hall is Alaska Young. The gorgeous, clever, funny, sexy, self-destructive, screwed up, and utterly fascinating Alaska Young. She is an event unto herself. She pulls Pudge into her world, launches him into the Great Perhaps, and steals his heart. Then. . . . After. Nothing is ever the same."
                        },
                        new
                        {
                            BookId = 16,
                            AuthorId = 5,
                            BookTitle = "The Notebook",
                            PublicationYear = new DateTime(1996, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Set amid the austere beauty of the North Carolina coast begins the story of Noah Calhoun, a rural Southerner recently returned from the Second World War. Noah is restoring a plantation home to its former glory, and he is haunted by images of the beautiful girl he met fourteen years earlier, a girl he loved like no other. Unable to find her, yet unwilling to forget the summer they spent together, Noah is content to live with only memories...until she unexpectedly returns to his town to see him once again. Like a puzzle within a puzzle, the story of Noah and Allie is just the beginning. As it unfolds, their tale miraculously becomes something different, with much higher stakes. The result is a deeply moving portrait of love itself, the tender moments and the fundamental changes that affect us all. It is a story of miracles and emotions that will stay with you forever."
                        },
                        new
                        {
                            BookId = 17,
                            AuthorId = 6,
                            BookTitle = "Fangirl",
                            PublicationYear = new DateTime(2013, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Cath is a Simon Snow fan. Okay, the whole world is a Simon Snow fan.... But for Cath, being a fan is her life—and she's really good at it. She and her twin, Wren, ensconced themselves in the Simon Snow series when they were just kids; it's what got them through their mother leaving. Reading. Rereading. Hanging out in Simon Snow forums, writing Simon Snow fanfiction, dressing up like the characters for every movie premiere. Cath's sister has mostly grown away from fandom, but Cath can't let go. She doesn't want to. Now that they're going to college, Wren has told Cath she doesn't want to be roommates. Cath is on her own, completely outside of her comfort zone. She's got a surly roommate with a charming, always-around boyfriend; a fiction-writing professor who thinks fanfiction is the end of the civilized world; a handsome classmate who only wants to talk about words... and she can't stop worrying about her dad, who's loving and fragile and has never really been alone. For Cath, the question is: Can she do this? Can she make it without Wren holding her hand? Is she ready to start living her own life? And does she even want to move on if it means leaving Simon Snow behind?"
                        },
                        new
                        {
                            BookId = 18,
                            AuthorId = 7,
                            BookTitle = "And Then There Were None",
                            PublicationYear = new DateTime(1939, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "First, there were ten—a curious assortment of strangers summoned as weekend guests to a little private island off the coast of Devon. Their host, an eccentric millionaire unknown to all of them, is nowhere to be found. All that the guests have in common is a wicked past they're unwilling to reveal—and a secret that will seal their fate. For each has been marked for murder. A famous nursery rhyme is framed and hung in every room of the mansion: \"Ten little boys went out to dine; One choked his little self and then there were nine. Nine little boys sat up very late; One overslept himself and then there were eight. Eight little boys traveling in Devon; One said he'd stay there then there were seven. Seven little boys chopping up sticks; One chopped himself in half and then there were six. Six little boys playing with a hive; A bumblebee stung one and then there were five. Five little boys going in for law; One got in Chancery and then there were four. Four little boys going out to sea; A red herring swallowed one and then there were three. Three little boys walking in the zoo; A big bear hugged one and then there were two. Two little boys sitting in the sun; One got frizzled up and then there was one. One little boy left all alone; He went out and hanged himself and then there were none.\" When they realize that murders are occurring as described in the rhyme, terror mounts. One by one they fall prey. Before the weekend is out, there will be none. Who has choreographed this dastardly scheme? And who will be left to tell the tale? Only the dead are above suspicion."
                        },
                        new
                        {
                            BookId = 19,
                            AuthorId = 8,
                            BookTitle = "Gone Girl",
                            PublicationYear = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Who are you? What have we done to each other? These are the questions Nick Dunne finds himself asking on the morning of his fifth wedding anniversary when his wife Amy suddenly disappears. The police suspect Nick. Amy's friends reveal that she was afraid of him, that she kept secrets from him. He swears it isn't true. A police examination of his computer shows strange searches. He says they weren't made by him. And then there are the persistent calls on his mobile phone. So what did happen to Nick's beautiful wife?"
                        },
                        new
                        {
                            BookId = 20,
                            AuthorId = 9,
                            BookTitle = "The Da Vinci Code",
                            PublicationYear = new DateTime(2003, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "While in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter. Even more startling, the late curator was involved in the Priory of Sion—a secret society whose members included Sir Isaac Newton, Victor Hugo, and Da Vinci—and he guarded a breathtaking historical secret. Unless Langdon and Neveu can decipher the labyrinthine puzzle—while avoiding the faceless adversary who shadows their every move—the explosive, ancient truth will be lost forever."
                        },
                        new
                        {
                            BookId = 21,
                            AuthorId = 10,
                            BookTitle = "A Good Girl's Guide to Murder",
                            PublicationYear = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "The case is closed. Five years ago, schoolgirl Andie Bell was murdered by Sal Singh. The police know he did it. Everyone in town knows he did it. But having grown up in the same small town that was consumed by the murder, Pippa Fitz-Amobi isn't so sure. When she chooses the case as the topic for her final year project, she starts to uncover secrets that someone in town desperately wants to stay hidden. And if the real killer is still out there, how far will they go to keep Pip from the truth?"
                        },
                        new
                        {
                            BookId = 22,
                            AuthorId = 11,
                            BookTitle = "In a Sunburned Country",
                            PublicationYear = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "It is the driest, flattest, hottest, most infertile and climatically aggressive of all the inhabited continents, and still Australia teems with life - a large portion of it quite deadly. In fact, Australia has more things that can kill you in a very nasty way than anywhere else. Ignoring such dangers - and yet curiously obsessed by them - Bill Bryson journeyed to Australia and promptly fell in love with the country. And who can blame him? The people are cheerful, extroverted, quick-witted and unfailingly obliging: their cities are safe and clean and nearly always built on water; the food is excellent; the beer is cold and the sun nearly always shines. Life doesn't get much better than this..."
                        },
                        new
                        {
                            BookId = 23,
                            AuthorId = 12,
                            BookTitle = "Into the Wild",
                            PublicationYear = new DateTime(1996, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "In April, 1992, a young man from a well-to-do family hitchhiked to Alaska and walked alone into the wilderness north of Mt. McKinley. His name was Christopher Johnson McCandless. He had given $25,000 in savings to charity, abandoned his car and most of his possessions, burned all the cash in his wallet, and invented a new life for himself. Four months later, a party of moose hunters found his decomposed body. How McCandless came to die is the unforgettable story of Into the Wild. Immediately after graduating from college in 1991, McCandless had roamed through the West and Southwest on a vision quest like those made by his heroes Jack London and John Muir. In the Mojave Desert he abandoned his car, stripped it of its license plates, and burned all of his cash. He would give himself a new name, Alexander Supertramp, and, unencumbered by money and belongings, he would be free to wallow in the raw, unfiltered experiences that nature presented. Craving a blank spot on the map, McCandless simply threw away the maps. Leaving behind his desperate parents and sister, he vanished into the wild."
                        },
                        new
                        {
                            BookId = 24,
                            AuthorId = 13,
                            BookTitle = "The Shining",
                            PublicationYear = new DateTime(1977, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to spend reconnecting with his family and working on his writing. But as the harsh winter weather sets in, the idyllic location feels ever more remote...and more sinister. And the only one to notice the strange and terrible forces gathering around the Overlook is Danny Torrance, a uniquely gifted five-year-old."
                        },
                        new
                        {
                            BookId = 25,
                            AuthorId = 13,
                            BookTitle = "It",
                            PublicationYear = new DateTime(1986, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Welcome to Derry, Maine ... It’s a small city, a place as hauntingly familiar as your own hometown. Only in Derry the haunting is real ... They were seven teenagers when they first stumbled upon the horror. Now they are grown-up men and women who have gone out into the big world to gain success and happiness. But none of them can withstand the force that has drawn them back to Derry to face the nightmare without an end, and the evil without a name."
                        },
                        new
                        {
                            BookId = 26,
                            AuthorId = 13,
                            BookTitle = "Carrie",
                            PublicationYear = new DateTime(1974, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "A modern classic, Carrie introduced a distinctive new voice in American fiction -- Stephen King. The story of misunderstood high school girl Carrie White, her extraordinary telekinetic powers, and her violent rampage of revenge, remains one of the most barrier-breaking and shocking novels of all time. Make a date with terror and live the nightmare that is...Carrie"
                        },
                        new
                        {
                            BookId = 27,
                            AuthorId = 13,
                            BookTitle = "The Green Mile",
                            PublicationYear = new DateTime(1996, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "At Cold Mountain Penitentiary, along the lonely stretch of cells known as the Green Mile, condemned killers such as 'Billy the Kid' Wharton and the possessed Eduard Delacroix await death strapped in 'Old Sparky'. But good or evil, innocent or guilty, prisoner or guard, none has ever seen the brutal likes of the new prisoner, John Coffey, sentenced to death for raping and murdering two young girls. Is Coffey a devil in human form? Or is he a far, far different kind of being? There are more wonders in heaven and hell than anyone at Cold Mountain can imagine and one of those wonders might just have stepped in amongst them."
                        },
                        new
                        {
                            BookId = 28,
                            AuthorId = 14,
                            BookTitle = "The Haunting of Hill House",
                            PublicationYear = new DateTime(1959, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "It is the story of four seekers who arrive at a notoriously unfriendly pile called Hill House: Dr. Montague, an occult scholar looking for solid evidence of a \"haunting\"; Theodora, the lighthearted assistant; Eleanor, a friendless, fragile young woman well acquainted with poltergeists; and Luke, the future heir of Hill House. At first, their stay seems destined to be merely a spooky encounter with inexplicable phenomena. But Hill House is gathering its powers—and soon it will choose one of them to make its own."
                        },
                        new
                        {
                            BookId = 29,
                            AuthorId = 15,
                            BookTitle = "Dracula",
                            PublicationYear = new DateTime(1897, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "When Jonathan Harker visits Transylvania to help Count Dracula with the purchase of a London house, he makes a series of horrific discoveries about his client. Soon afterwards, various bizarre incidents unfold in England: an apparently unmanned ship is wrecked off the coast of Whitby; a young woman discovers strange puncture marks on her neck; and the inmate of a lunatic asylum raves about the 'Master' and his imminent arrival."
                        },
                        new
                        {
                            BookId = 30,
                            AuthorId = 16,
                            BookTitle = "Why We Sleep: Unlocking the Power of Sleep and Dreams",
                            PublicationYear = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Neuroscientist and sleep expert Matthew Walker provides a revolutionary exploration of sleep, examining how it affects every aspect of our physical and mental well-being. Charting the most cutting-edge scientific breakthroughs, and marshalling his decades of research and clinical practice, Walker explains how we can harness sleep to improve learning, mood and energy levels, regulate hormones, prevent cancer, Alzheimer's and diabetes, slow the effects of aging, and increase longevity. He also provides actionable steps towards getting a better night's sleep every night."
                        },
                        new
                        {
                            BookId = 31,
                            AuthorId = 17,
                            BookTitle = "In Defense of Food: An Eater's Manifesto",
                            PublicationYear = new DateTime(2008, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Michael Pollan's last book, The Omnivore's Dilemma, launched a national conversation about the American way of eating; now In Defense of Food shows us how to change it, one meal at a time. Pollan proposes a new answer to the question of what we should eat that comes down to seven simple but liberating words: Eat food. Not too much. Mostly plants. Pollan's bracing and eloquent manifesto shows us how we can start making thoughtful food choices that will enrich our lives, enlarge our sense of what it means to be healthy, and bring pleasure back to eating."
                        },
                        new
                        {
                            BookId = 32,
                            AuthorId = 18,
                            BookTitle = "Joy of Cooking",
                            PublicationYear = new DateTime(1931, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "You will find tried-and-true favorites like Banana Bread Cockaigne, Chocolate Chip Cookies, and Southern Corn Bread—all retested and faithfully improved—as well as new favorites like Chana Masala, Beef Rendang, Megan’s Seeded Olive Oil Granola, and Smoked Pork Shoulder. In addition to a thoroughly modernized vegetable chapter, there are many more vegan and vegetarian recipes, including Caramelized Tamarind Tempeh, Crispy Pan-Fried Tofu, Spicy Chickpea Soup, and Roasted Mushroom Burgers. Joy’s baking chapters now include gram weights for accuracy, along with a refreshed lineup of baked goods like Cannelés de Bordeaux, Rustic No-Knead Sourdough, Ciabatta, Chocolate-Walnut Babka, and Chicago-Style Deep-Dish Pizza, as well as gluten-free recipes for pizza dough and yeast breads."
                        },
                        new
                        {
                            BookId = 33,
                            AuthorId = 19,
                            BookTitle = "Mastering the Art of French Cooking",
                            PublicationYear = new DateTime(1961, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "or over fifty years, New York Times bestseller Mastering the Art of French Cooking has been the definitive book on the subject for American readers. Featuring 524 delicious recipes, in its pages home cooks will find something for everyone, from seasoned experts to beginners who love good food and long to reproduce the savory delights of French cuisine, from historic Gallic masterpieces to the seemingly artless perfection of a dish of spring-green peas. Here Julia Child, Simone Beck, and Louisette Bertholle break down the classic foods of France into a logical sequence of themes and variations rather than presenting an endless and diffuse catalogue of dishes. Throughout, the focus is on key recipes that form the backbone of French cookery and lend themselves to an infinite number of elaborations--bound to increase anyone's culinary repertoire. With over 100 instructive illustrations to guide readers every step of the way, Mastering the Art of French Cooking deserves a place of honor in every kitchen in America."
                        });
                });

            modelBuilder.Entity("Core.Persistence.Entities.Genres", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GenreName = "Fantasy"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreName = "Adventure"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreName = "Romance"
                        },
                        new
                        {
                            GenreId = 4,
                            GenreName = "Mystery"
                        },
                        new
                        {
                            GenreId = 5,
                            GenreName = "Horror"
                        },
                        new
                        {
                            GenreId = 6,
                            GenreName = "Historical Fiction"
                        },
                        new
                        {
                            GenreId = 7,
                            GenreName = "Cooking"
                        },
                        new
                        {
                            GenreId = 8,
                            GenreName = "History"
                        },
                        new
                        {
                            GenreId = 9,
                            GenreName = "Health"
                        },
                        new
                        {
                            GenreId = 10,
                            GenreName = "Travel"
                        },
                        new
                        {
                            GenreId = 11,
                            GenreName = "Fiction"
                        },
                        new
                        {
                            GenreId = 12,
                            GenreName = "Young Adult"
                        },
                        new
                        {
                            GenreId = 13,
                            GenreName = "Middle Grade"
                        },
                        new
                        {
                            GenreId = 14,
                            GenreName = "Adult"
                        },
                        new
                        {
                            GenreId = 15,
                            GenreName = "Crime"
                        },
                        new
                        {
                            GenreId = 16,
                            GenreName = "Thriller"
                        },
                        new
                        {
                            GenreId = 17,
                            GenreName = "Non-Fiction"
                        });
                });

            modelBuilder.Entity("Core.Persistence.Entities.GenresInBook", b =>
                {
                    b.Property<int>("GenresInBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenresInBookId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("GenresInBookId");

                    b.HasIndex("BookId");

                    b.HasIndex("GenreId");

                    b.ToTable("GenresInBook");

                    b.HasData(
                        new
                        {
                            GenresInBookId = 1,
                            BookId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 2,
                            BookId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 3,
                            BookId = 1,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 4,
                            BookId = 1,
                            GenreId = 13
                        },
                        new
                        {
                            GenresInBookId = 5,
                            BookId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 6,
                            BookId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 7,
                            BookId = 2,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 8,
                            BookId = 2,
                            GenreId = 13
                        },
                        new
                        {
                            GenresInBookId = 9,
                            BookId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 10,
                            BookId = 3,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 11,
                            BookId = 3,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 12,
                            BookId = 3,
                            GenreId = 13
                        },
                        new
                        {
                            GenresInBookId = 13,
                            BookId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 14,
                            BookId = 4,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 15,
                            BookId = 4,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 16,
                            BookId = 4,
                            GenreId = 13
                        },
                        new
                        {
                            GenresInBookId = 17,
                            BookId = 5,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 18,
                            BookId = 5,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 19,
                            BookId = 5,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 20,
                            BookId = 5,
                            GenreId = 13
                        },
                        new
                        {
                            GenresInBookId = 21,
                            BookId = 6,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 22,
                            BookId = 6,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 23,
                            BookId = 6,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 24,
                            BookId = 6,
                            GenreId = 13
                        },
                        new
                        {
                            GenresInBookId = 25,
                            BookId = 7,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 26,
                            BookId = 7,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 27,
                            BookId = 7,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 28,
                            BookId = 7,
                            GenreId = 13
                        },
                        new
                        {
                            GenresInBookId = 29,
                            BookId = 8,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 30,
                            BookId = 8,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 31,
                            BookId = 8,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 32,
                            BookId = 8,
                            GenreId = 13
                        },
                        new
                        {
                            GenresInBookId = 33,
                            BookId = 9,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 34,
                            BookId = 9,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 35,
                            BookId = 9,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 36,
                            BookId = 9,
                            GenreId = 12
                        },
                        new
                        {
                            GenresInBookId = 37,
                            BookId = 10,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 38,
                            BookId = 10,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 39,
                            BookId = 10,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 40,
                            BookId = 10,
                            GenreId = 12
                        },
                        new
                        {
                            GenresInBookId = 41,
                            BookId = 11,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 42,
                            BookId = 11,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 43,
                            BookId = 11,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 44,
                            BookId = 11,
                            GenreId = 12
                        },
                        new
                        {
                            GenresInBookId = 45,
                            BookId = 12,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 46,
                            BookId = 12,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 47,
                            BookId = 12,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 48,
                            BookId = 12,
                            GenreId = 12
                        },
                        new
                        {
                            GenresInBookId = 49,
                            BookId = 13,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 50,
                            BookId = 13,
                            GenreId = 3
                        },
                        new
                        {
                            GenresInBookId = 51,
                            BookId = 13,
                            GenreId = 6
                        },
                        new
                        {
                            GenresInBookId = 52,
                            BookId = 13,
                            GenreId = 4
                        },
                        new
                        {
                            GenresInBookId = 53,
                            BookId = 14,
                            GenreId = 3
                        },
                        new
                        {
                            GenresInBookId = 54,
                            BookId = 14,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 55,
                            BookId = 14,
                            GenreId = 12
                        },
                        new
                        {
                            GenresInBookId = 56,
                            BookId = 15,
                            GenreId = 3
                        },
                        new
                        {
                            GenresInBookId = 57,
                            BookId = 15,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 58,
                            BookId = 15,
                            GenreId = 12
                        },
                        new
                        {
                            GenresInBookId = 59,
                            BookId = 16,
                            GenreId = 3
                        },
                        new
                        {
                            GenresInBookId = 60,
                            BookId = 16,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 61,
                            BookId = 16,
                            GenreId = 12
                        },
                        new
                        {
                            GenresInBookId = 62,
                            BookId = 17,
                            GenreId = 3
                        },
                        new
                        {
                            GenresInBookId = 63,
                            BookId = 17,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 64,
                            BookId = 17,
                            GenreId = 12
                        },
                        new
                        {
                            GenresInBookId = 65,
                            BookId = 18,
                            GenreId = 15
                        },
                        new
                        {
                            GenresInBookId = 66,
                            BookId = 18,
                            GenreId = 16
                        },
                        new
                        {
                            GenresInBookId = 67,
                            BookId = 18,
                            GenreId = 4
                        },
                        new
                        {
                            GenresInBookId = 68,
                            BookId = 18,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 69,
                            BookId = 19,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 70,
                            BookId = 19,
                            GenreId = 4
                        },
                        new
                        {
                            GenresInBookId = 71,
                            BookId = 19,
                            GenreId = 16
                        },
                        new
                        {
                            GenresInBookId = 72,
                            BookId = 19,
                            GenreId = 15
                        },
                        new
                        {
                            GenresInBookId = 73,
                            BookId = 19,
                            GenreId = 14
                        },
                        new
                        {
                            GenresInBookId = 74,
                            BookId = 20,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 75,
                            BookId = 20,
                            GenreId = 4
                        },
                        new
                        {
                            GenresInBookId = 76,
                            BookId = 20,
                            GenreId = 16
                        },
                        new
                        {
                            GenresInBookId = 77,
                            BookId = 20,
                            GenreId = 15
                        },
                        new
                        {
                            GenresInBookId = 78,
                            BookId = 20,
                            GenreId = 14
                        },
                        new
                        {
                            GenresInBookId = 79,
                            BookId = 21,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 80,
                            BookId = 21,
                            GenreId = 4
                        },
                        new
                        {
                            GenresInBookId = 81,
                            BookId = 21,
                            GenreId = 16
                        },
                        new
                        {
                            GenresInBookId = 82,
                            BookId = 21,
                            GenreId = 15
                        },
                        new
                        {
                            GenresInBookId = 83,
                            BookId = 21,
                            GenreId = 12
                        },
                        new
                        {
                            GenresInBookId = 84,
                            BookId = 22,
                            GenreId = 17
                        },
                        new
                        {
                            GenresInBookId = 85,
                            BookId = 22,
                            GenreId = 8
                        },
                        new
                        {
                            GenresInBookId = 86,
                            BookId = 22,
                            GenreId = 10
                        },
                        new
                        {
                            GenresInBookId = 87,
                            BookId = 23,
                            GenreId = 10
                        },
                        new
                        {
                            GenresInBookId = 88,
                            BookId = 23,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 89,
                            BookId = 23,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 90,
                            BookId = 24,
                            GenreId = 5
                        },
                        new
                        {
                            GenresInBookId = 91,
                            BookId = 24,
                            GenreId = 4
                        },
                        new
                        {
                            GenresInBookId = 92,
                            BookId = 24,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 93,
                            BookId = 24,
                            GenreId = 14
                        },
                        new
                        {
                            GenresInBookId = 94,
                            BookId = 24,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 95,
                            BookId = 25,
                            GenreId = 5
                        },
                        new
                        {
                            GenresInBookId = 96,
                            BookId = 25,
                            GenreId = 4
                        },
                        new
                        {
                            GenresInBookId = 97,
                            BookId = 25,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 98,
                            BookId = 25,
                            GenreId = 16
                        },
                        new
                        {
                            GenresInBookId = 99,
                            BookId = 25,
                            GenreId = 14
                        },
                        new
                        {
                            GenresInBookId = 100,
                            BookId = 25,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 101,
                            BookId = 26,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 102,
                            BookId = 26,
                            GenreId = 5
                        },
                        new
                        {
                            GenresInBookId = 103,
                            BookId = 26,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 104,
                            BookId = 26,
                            GenreId = 16
                        },
                        new
                        {
                            GenresInBookId = 105,
                            BookId = 26,
                            GenreId = 14
                        },
                        new
                        {
                            GenresInBookId = 106,
                            BookId = 27,
                            GenreId = 5
                        },
                        new
                        {
                            GenresInBookId = 107,
                            BookId = 27,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 108,
                            BookId = 27,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 109,
                            BookId = 27,
                            GenreId = 16
                        },
                        new
                        {
                            GenresInBookId = 110,
                            BookId = 27,
                            GenreId = 4
                        },
                        new
                        {
                            GenresInBookId = 111,
                            BookId = 27,
                            GenreId = 15
                        },
                        new
                        {
                            GenresInBookId = 112,
                            BookId = 27,
                            GenreId = 6
                        },
                        new
                        {
                            GenresInBookId = 113,
                            BookId = 28,
                            GenreId = 5
                        },
                        new
                        {
                            GenresInBookId = 114,
                            BookId = 28,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 115,
                            BookId = 28,
                            GenreId = 4
                        },
                        new
                        {
                            GenresInBookId = 116,
                            BookId = 28,
                            GenreId = 14
                        },
                        new
                        {
                            GenresInBookId = 117,
                            BookId = 28,
                            GenreId = 16
                        },
                        new
                        {
                            GenresInBookId = 118,
                            BookId = 29,
                            GenreId = 5
                        },
                        new
                        {
                            GenresInBookId = 119,
                            BookId = 29,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 120,
                            BookId = 29,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 121,
                            BookId = 30,
                            GenreId = 17
                        },
                        new
                        {
                            GenresInBookId = 122,
                            BookId = 30,
                            GenreId = 9
                        },
                        new
                        {
                            GenresInBookId = 123,
                            BookId = 31,
                            GenreId = 17
                        },
                        new
                        {
                            GenresInBookId = 124,
                            BookId = 31,
                            GenreId = 9
                        },
                        new
                        {
                            GenresInBookId = 125,
                            BookId = 31,
                            GenreId = 7
                        },
                        new
                        {
                            GenresInBookId = 126,
                            BookId = 32,
                            GenreId = 7
                        },
                        new
                        {
                            GenresInBookId = 127,
                            BookId = 32,
                            GenreId = 17
                        },
                        new
                        {
                            GenresInBookId = 128,
                            BookId = 33,
                            GenreId = 7
                        },
                        new
                        {
                            GenresInBookId = 129,
                            BookId = 33,
                            GenreId = 17
                        });
                });

            modelBuilder.Entity("Core.Persistence.Entities.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("HasLoggedInBefore")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LoginUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Persistence.Entities.Books", b =>
                {
                    b.HasOne("Core.Persistence.Entities.Authors", "Authors")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authors");
                });

            modelBuilder.Entity("Core.Persistence.Entities.GenresInBook", b =>
                {
                    b.HasOne("Core.Persistence.Entities.Books", "Books")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Persistence.Entities.Genres", "Genres")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Books");

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
