// <auto-generated />
using System;
using Core.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230417093346_AddMembershipIsActive")]
    partial class AddMembershipIsActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Persistence.Entities.Authors", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("AuthorFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            AuthorFirstName = "M.R.",
                            AuthorLastName = "James"
                        },
                        new
                        {
                            AuthorId = 2,
                            AuthorFirstName = "Bob",
                            AuthorLastName = "Brown"
                        },
                        new
                        {
                            AuthorId = 3,
                            AuthorFirstName = "Wilkie",
                            AuthorLastName = "Collins"
                        },
                        new
                        {
                            AuthorId = 4,
                            AuthorFirstName = "Joseph",
                            AuthorLastName = "Conrad"
                        },
                        new
                        {
                            AuthorId = 5,
                            AuthorFirstName = "P. G.",
                            AuthorLastName = "Wodehouse"
                        },
                        new
                        {
                            AuthorId = 6,
                            AuthorFirstName = "Charles",
                            AuthorLastName = "Garvice"
                        },
                        new
                        {
                            AuthorId = 7,
                            AuthorFirstName = "Alexandre",
                            AuthorLastName = "Dumas"
                        },
                        new
                        {
                            AuthorId = 8,
                            AuthorFirstName = "Victor",
                            AuthorLastName = "Hugo"
                        },
                        new
                        {
                            AuthorId = 9,
                            AuthorFirstName = "Jack",
                            AuthorLastName = "London"
                        });
                });

            modelBuilder.Entity("Core.Persistence.Entities.BookLists", b =>
                {
                    b.Property<int>("BookListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookListId"));

                    b.Property<string>("BookListName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookListId");

                    b.HasIndex("UserId");

                    b.ToTable("BookLists");
                });

            modelBuilder.Entity("Core.Persistence.Entities.Books", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("BookCover")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookPdfUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublicationYear")
                        .HasColumnType("DATE");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            BookCover = "GhostStoriesOfAnAntiquary.jpg",
                            BookPdfUrl = "GhostStoriesOfAnAntiquary.pdf",
                            BookTitle = "Ghost Stories of an Antiquary",
                            PublicationYear = new DateTime(1904, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Eight classics by a great Edwardian scholar and storyteller. \"Number Thirteen,\" \"The Mezzotint,\" \"Canon Alberic's Scrapbook,\" and more. Renowned for their wit, erudition and suspense, these stories are each masterfully constructed and represent a high achievement in the ghost genre. We are delighted to publish this classic book as part of our extensive Classic Library collection. Many of the books in our collection have been out of print for decades, and therefore have not been accessible to the general public. The aim of our publishing program is to facilitate rapid access to this vast reservoir of literature, and our view is that this is a significant literary work, which deserves to be brought back into print after many decades. The contents of the vast majority of titles in the Classic Library have been scanned from the original works. To ensure a high quality product, each title has been meticulously hand curated by our staff. Our philosophy has been guided by a desire to provide the reader with a book that is as close as possible to ownership of the original work. We hope that you will enjoy this wonderful classic work, and that for you it becomes an enriching experience."
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2,
                            BookCover = "TheCompleteBookOfCheese.jpg",
                            BookPdfUrl = "TheCompleteBookOfCheese.pdf",
                            BookTitle = "The Complete Book of Cheese",
                            PublicationYear = new DateTime(1955, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "1. I Remember Cheese 2. The Big Cheese 3. Foreign Greats 4. Native Americans 5. Sixty-five Sizzling Rabbits 6. The Fondue 7. Soufflés, Puffs and Ramekins 8. Pizzas, Blintzes, Pastes and Cheese Cake 9. Au Gratin, Soups, Salads and Sauces 10. Appetizers, Crackers, Sandwiches, Savories, Snacks, Spreads and Toasts 11. \"Fit for Drink\" 12. Lazy Lou APPENDIX—The A-B-Z of Cheese"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 3,
                            BookCover = "TheWomanInWhite.jpg",
                            BookPdfUrl = "TheWomanInWhite.pdf",
                            BookTitle = "The Woman in White",
                            PublicationYear = new DateTime(1859, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "'In one moment, every drop of blood in my body was brought to a stop... There, as if it had that moment sprung out of the earth, stood the figure of a solitary Woman, dressed from head to foot in white' The Woman in White famously opens with Walter Hartright's eerie encounter on a moonlit London road. Engaged as a drawing master to the beautiful Laura Fairlie, Walter becomes embroiled in the sinister intrigues of Sir Percival Glyde and his 'charming' friend Count Fosco, who has a taste for white mice, vanilla bonbons, and poison. Pursuing questions of identity and insanity along the paths and corridors of English country houses and the madhouse, The Woman in White is the first and most influential of the Victorian genre that combined Gothic horror with psychological realism. Matthew Sweet's introduction explores the phenomenon of Victorian 'sensation' fiction, and discusses Wilkie Collins's biographical and societal influences. Included in this edition are appendices on theatrical adaptations of the novel and its serialisation history."
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 4,
                            BookCover = "TheSimpleAgentASimpleTale.jpg",
                            BookPdfUrl = "TheSimpleAgentASimpleTale.pdf",
                            BookTitle = "The Secret Agent: A Simple Tale",
                            PublicationYear = new DateTime(1907, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "In a rough-and-ready shop in Soho in Victorian London, Mr. Verloc lives a humble existence sustaining himself, his wife, her infirm mother, and her disabled brother, Stevie. But all is not as it seems with Mr. Verloc, a secret agent in the employ of a foreign government. When a plot to bomb Greenwich Observatory falls apart, Verloc’s identity is exposed, and those closest to him must bear the burden of his failures. Harkening back to the writings of Charles Dickens, Joseph Conrad’s early masterpiece effectively explores themes of subversion, politics, and crime.)"
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 5,
                            BookCover = "RightHoJeeves.jpg",
                            BookPdfUrl = "RightHoJeeves.pdf",
                            BookTitle = "Right Ho, Jeeves",
                            PublicationYear = new DateTime(1934, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Gussie Fink-Nottle has locked himself away in the country studying newts ever since he came into his estate. So it is a surprise when Bertie hears that Gussie is not only in London, but he is there to woo Madeline Bassett! At odds with Jeeves over the decorum of a white jacket, Bertie decides to take on Gussie's problem himself. Off to Brinkley Court, Bertie must deal with the prize-giving at Market Snodsbury Grammar School, the broken engagement of his cousin Angela, and the resignation of Anatole, his aunt's genius chef. Will Jeeves be able to sort out the mess?"
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 6,
                            BookCover = "OnlyAGirlsLove.jpg",
                            BookPdfUrl = "OnlyAGirlsLove.pdf",
                            BookTitle = "Only a Girl's Love",
                            PublicationYear = new DateTime(1979, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "It is a warm evening in early Summer; the sun is setting behind a long range of fir and yew-clad hills, at the feet of which twists in and out, as it follows their curves, a placid, peaceful river. Opposite these hills, and running beside the river, are long-stretching meadows, brilliantly green with fresh-springing grass, and gorgeously yellow with newly-opened buttercups. Above, the sunset sky gleams and glows with fiery red and rich deep chromes. And London is almost within sight. It is a beautiful scene, such as one sees only in this England of ours--a scene that defies poet and painter. At this very moment it is defying one of the latter genus; for in a room of a low-browed, thatched-roofed cottage which stood on the margin of the meadow, James Etheridge sat beside his easel, his eyes fixed on the picture framed in the open window, his brush and mahl-stick drooping in his idle hand"
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 7,
                            BookCover = "TwentyYearsAfter.jpg",
                            BookPdfUrl = "TwentyYearsAfter.pdf",
                            BookTitle = "Twenty Years After",
                            PublicationYear = new DateTime(1845, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Twenty Years After (1845), the sequel to The Three Musketeers, is a supreme creation of suspense and heroic adventure. Two decades have passed since the musketeers triumphed over Cardinal Richelieu and Milady. Time has weakened their resolve, and dispersed their loyalties. But treasons and stratagems still cry out for justice: civil war endangers the throne of France, while in England Cromwell threatens to send Charles I to the scaffold. Dumas brings his immortal quartet out of retirement to cross swords with time, the malevolence of men, and the forces of history. But their greatest test is a titanic struggle with the son of Milady, who wears the face of Evil."
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 8,
                            BookCover = "LesMiserables.jpg",
                            BookPdfUrl = "LesMiserables.pdf",
                            BookTitle = "Les Misérables",
                            PublicationYear = new DateTime(1862, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Victor Hugo's tale of injustice, heroism and love follows the fortunes of Jean Valjean, an escaped convict determined to put his criminal past behind him. But his attempts to become a respected member of the community are constantly put under threat: by his own conscience, when, owing to a case of mistaken identity, another man is arrested in his place; and by the relentless investigations of the dogged Inspector Javert. It is not simply for himself that Valjean must stay free, however, for he has sworn to protect the baby daughter of Fantine, driven to prostitution by poverty."
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 9,
                            BookCover = "TheCallOfTheWild.jpg",
                            BookPdfUrl = "TheCallOfTheWild.pdf",
                            BookTitle = "The Call of the Wild",
                            PublicationYear = new DateTime(1903, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "First published in 1903, The Call of the Wild is regarded as Jack London's masterpiece. Based on London's experiences as a gold prospector in the Canadian wilderness and his ideas about nature and the struggle for existence, The Call of the Wild is a tale about unbreakable spirit and the fight for survival in the frozen Alaskan Klondike."
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 7,
                            BookCover = "TheThreeMusketeers.jpg",
                            BookPdfUrl = "TheThreeMusketeers.pdf",
                            BookTitle = "The Three Musketeers",
                            PublicationYear = new DateTime(1844, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Alexandre Dumas’s most famous tale— and possibly the most famous historical novel of all time— in a handsome hardcover volume. This swashbuckling epic of chivalry, honor, and derring-do, set in France during the 1620s, is richly populated with romantic heroes, unattainable heroines, kings, queens, cavaliers, and criminals in a whirl of adventure, espionage, conspiracy, murder, vengeance, love, scandal, and suspense. Dumas transforms minor historical figures into larger- than-life characters: the Comte d’Artagnan, an impetuous young man in pursuit of glory; the beguilingly evil seductress “Milady”; the powerful and devious Cardinal Richelieu; the weak King Louis XIII and his unhappy queen—and, of course, the three musketeers themselves, Athos, Porthos, and Aramis, whose motto “all for one, one for all” has come to epitomize devoted friendship. With a plot that delivers stolen diamonds, masked balls, purloined letters, and, of course, great bouts of swordplay, The Three Musketeers is eternally entertaining."
                        });
                });

            modelBuilder.Entity("Core.Persistence.Entities.DigitalLicence", b =>
                {
                    b.Property<int>("LicenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenceId"));

                    b.Property<string>("LicenceKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenceXml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LicenceId");

                    b.HasIndex("UserId");

                    b.ToTable("DigitalLicence");
                });

            modelBuilder.Entity("Core.Persistence.Entities.Genres", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GenreName = "Fantasy"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreName = "Adventure"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreName = "Romance"
                        },
                        new
                        {
                            GenreId = 4,
                            GenreName = "Mystery"
                        },
                        new
                        {
                            GenreId = 5,
                            GenreName = "Horror"
                        },
                        new
                        {
                            GenreId = 6,
                            GenreName = "Historical Fiction"
                        },
                        new
                        {
                            GenreId = 7,
                            GenreName = "Cooking"
                        },
                        new
                        {
                            GenreId = 8,
                            GenreName = "Classics"
                        },
                        new
                        {
                            GenreId = 9,
                            GenreName = "Health"
                        },
                        new
                        {
                            GenreId = 10,
                            GenreName = "Fiction"
                        },
                        new
                        {
                            GenreId = 11,
                            GenreName = "Literature"
                        },
                        new
                        {
                            GenreId = 12,
                            GenreName = "Crime"
                        },
                        new
                        {
                            GenreId = 13,
                            GenreName = "Thriller"
                        },
                        new
                        {
                            GenreId = 14,
                            GenreName = "Non-Fiction"
                        },
                        new
                        {
                            GenreId = 15,
                            GenreName = "Humour"
                        });
                });

            modelBuilder.Entity("Core.Persistence.Entities.GenresInBook", b =>
                {
                    b.Property<int>("GenresInBookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenresInBookId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("GenresInBookId");

                    b.HasIndex("BookId");

                    b.HasIndex("GenreId");

                    b.ToTable("GenresInBook");

                    b.HasData(
                        new
                        {
                            GenresInBookId = 1,
                            BookId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            GenresInBookId = 2,
                            BookId = 1,
                            GenreId = 10
                        },
                        new
                        {
                            GenresInBookId = 3,
                            BookId = 1,
                            GenreId = 5
                        },
                        new
                        {
                            GenresInBookId = 4,
                            BookId = 2,
                            GenreId = 14
                        },
                        new
                        {
                            GenresInBookId = 5,
                            BookId = 2,
                            GenreId = 7
                        },
                        new
                        {
                            GenresInBookId = 6,
                            BookId = 3,
                            GenreId = 10
                        },
                        new
                        {
                            GenresInBookId = 7,
                            BookId = 3,
                            GenreId = 6
                        },
                        new
                        {
                            GenresInBookId = 8,
                            BookId = 3,
                            GenreId = 4
                        },
                        new
                        {
                            GenresInBookId = 9,
                            BookId = 3,
                            GenreId = 13
                        },
                        new
                        {
                            GenresInBookId = 10,
                            BookId = 3,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 11,
                            BookId = 3,
                            GenreId = 8
                        },
                        new
                        {
                            GenresInBookId = 12,
                            BookId = 4,
                            GenreId = 8
                        },
                        new
                        {
                            GenresInBookId = 13,
                            BookId = 4,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 14,
                            BookId = 4,
                            GenreId = 4
                        },
                        new
                        {
                            GenresInBookId = 15,
                            BookId = 4,
                            GenreId = 12
                        },
                        new
                        {
                            GenresInBookId = 16,
                            BookId = 4,
                            GenreId = 13
                        },
                        new
                        {
                            GenresInBookId = 17,
                            BookId = 5,
                            GenreId = 15
                        },
                        new
                        {
                            GenresInBookId = 18,
                            BookId = 5,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 19,
                            BookId = 5,
                            GenreId = 10
                        },
                        new
                        {
                            GenresInBookId = 20,
                            BookId = 5,
                            GenreId = 6
                        },
                        new
                        {
                            GenresInBookId = 21,
                            BookId = 6,
                            GenreId = 3
                        },
                        new
                        {
                            GenresInBookId = 22,
                            BookId = 6,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 23,
                            BookId = 6,
                            GenreId = 10
                        },
                        new
                        {
                            GenresInBookId = 24,
                            BookId = 7,
                            GenreId = 10
                        },
                        new
                        {
                            GenresInBookId = 25,
                            BookId = 7,
                            GenreId = 8
                        },
                        new
                        {
                            GenresInBookId = 26,
                            BookId = 7,
                            GenreId = 6
                        },
                        new
                        {
                            GenresInBookId = 27,
                            BookId = 7,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 28,
                            BookId = 7,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 29,
                            BookId = 8,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 30,
                            BookId = 8,
                            GenreId = 8
                        },
                        new
                        {
                            GenresInBookId = 31,
                            BookId = 8,
                            GenreId = 6
                        },
                        new
                        {
                            GenresInBookId = 32,
                            BookId = 8,
                            GenreId = 10
                        },
                        new
                        {
                            GenresInBookId = 33,
                            BookId = 8,
                            GenreId = 3
                        },
                        new
                        {
                            GenresInBookId = 34,
                            BookId = 9,
                            GenreId = 8
                        },
                        new
                        {
                            GenresInBookId = 35,
                            BookId = 9,
                            GenreId = 10
                        },
                        new
                        {
                            GenresInBookId = 36,
                            BookId = 9,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 37,
                            BookId = 9,
                            GenreId = 6
                        },
                        new
                        {
                            GenresInBookId = 38,
                            BookId = 9,
                            GenreId = 11
                        },
                        new
                        {
                            GenresInBookId = 39,
                            BookId = 10,
                            GenreId = 10
                        },
                        new
                        {
                            GenresInBookId = 40,
                            BookId = 10,
                            GenreId = 8
                        },
                        new
                        {
                            GenresInBookId = 41,
                            BookId = 10,
                            GenreId = 6
                        },
                        new
                        {
                            GenresInBookId = 42,
                            BookId = 10,
                            GenreId = 2
                        },
                        new
                        {
                            GenresInBookId = 43,
                            BookId = 10,
                            GenreId = 11
                        });
                });

            modelBuilder.Entity("Core.Persistence.Entities.Membership", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipId"));

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalBooks")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MembershipId");

                    b.HasIndex("UserId");

                    b.ToTable("Membership");
                });

            modelBuilder.Entity("Core.Persistence.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("MembershipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentId");

                    b.HasIndex("MembershipId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Core.Persistence.Entities.UserBookLists", b =>
                {
                    b.Property<int>("UserBookListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserBookListId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("BookListId")
                        .HasColumnType("int");

                    b.HasKey("UserBookListId");

                    b.HasIndex("BookId");

                    b.HasIndex("BookListId");

                    b.ToTable("UserBookLists");
                });

            modelBuilder.Entity("Core.Persistence.Entities.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("HasLoggedInBefore")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LoginUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Admin",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "RegisteredUser",
                            ConcurrencyStamp = "2",
                            Name = "RegisteredUser",
                            NormalizedName = "REGISTEREDUSER"
                        },
                        new
                        {
                            Id = "PaidMember",
                            ConcurrencyStamp = "3",
                            Name = "PaidMember",
                            NormalizedName = "PAIDMEMBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Persistence.Entities.BookLists", b =>
                {
                    b.HasOne("Core.Persistence.Entities.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Core.Persistence.Entities.Books", b =>
                {
                    b.HasOne("Core.Persistence.Entities.Authors", "Authors")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authors");
                });

            modelBuilder.Entity("Core.Persistence.Entities.DigitalLicence", b =>
                {
                    b.HasOne("Core.Persistence.Entities.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Core.Persistence.Entities.GenresInBook", b =>
                {
                    b.HasOne("Core.Persistence.Entities.Books", "Books")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Persistence.Entities.Genres", "Genres")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Books");

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("Core.Persistence.Entities.Membership", b =>
                {
                    b.HasOne("Core.Persistence.Entities.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Core.Persistence.Entities.Payment", b =>
                {
                    b.HasOne("Core.Persistence.Entities.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Core.Persistence.Entities.UserBookLists", b =>
                {
                    b.HasOne("Core.Persistence.Entities.Books", "Books")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Persistence.Entities.BookLists", "BookLists")
                        .WithMany()
                        .HasForeignKey("BookListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookLists");

                    b.Navigation("Books");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
